pipeline:
    build:
        image: alpine:3.7
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - apk add --update docker make
            - ./configure
            - make build

    branches: feature/build-drone
